# Displacing the Classical Pascal Triangle

## Pascal Triangle

The Pascal's triangle is classically defined on the space of naturals numbers, $\mathbb{N} \times \mathbb{N}$, forming a lower/left triangular matrix filled with the corresponding binomial coefficient.

Let's accept its extention to the space of integers, $\mathbb{Z} \times \mathbb{Z}$, by simply filling the negative parts of the domain with $0$, as follows:

$\forall \ n, k \in \mathbb{Z} :$

$$ \mathcal{Z}\binom{n}{k} = \begin{cases} 
  \binom{n}{k} \ & \text{ if } n \geq k \geq 0\\
  0 & \text{otherwise}
\end{cases}$$


## Displaced Pascal Triangle

The "origin" cell $(0,0)$ can be displaced to another position $(b, d)$ into the matrix.

Let's use $b$ for the initial budget (shifting the $k$ axis), and $d$ for an initial delay (displacing the $n$ axis).

### $b$-Shifted Pascal Triangle

The triangle is "shifted" in the $k$ axis by $b$:

$ \mathcal{Shift}_{b}\mathcal{Z}\binom{n}{k} = \mathcal{Z}\binom{n}{k-b} = 
\begin{cases}
\binom{n}{k-b} & \text{ if } n \geq (k-b) \geq 0 \\
0 & \text{ otherwise }
\end{cases}$

### $d$-Delayed Pascal Triangle

The triangle is "delayed" in the $n$ axis by $d$:

$ \mathcal{Delay}_{d}\mathcal{Z}\binom{n}{k} = \mathcal{Z}\binom{n-d}{k} = 
\begin{cases}
\binom{n-d}{k} & \text{ if } (n-d) \geq k \geq 0\\
0 & \text{ otherwise }
\end{cases}$

### $(d,b)$-Transposed Pascal Triangle

$ \mathcal{T}\!\mathcal{rans}_{d,b}\mathcal{Z}\binom{n}{k} = \mathcal{Z}\binom{n-d}{k-b} = 
\begin{cases}
\binom{n-d}{k-b} & \text{ if } (n-d) \geq (k-b) \geq 0\\
0 & \text{ otherwise }
\end{cases}$

In [1]:
from pyrl.gr import *
from pyrl.utils import printdf

################

max_n = 20
k_arr = range(-3,max_n+1)
n_arr = range(-3,max_n+1)

printdf([[delay_pascal_triangle(n, k, 3) for k in k_arr] for n in n_arr], label_rows=n_arr, label_cols=k_arr, label_axis_cols="$k$", label_axis_rows="$n$",  title='$+3$-Delayed Pascal Triangle:')
printdf([[shift_pascal_triangle(n, k, 3) for k in k_arr] for n in n_arr], label_rows=n_arr, label_cols=k_arr, label_axis_cols="$k$", label_axis_rows="$n$", title='$+3$-Shifted Pascal Triangle:')
printdf([[trans_pascal_triangle(n, k, -2, -1) for k in k_arr] for n in n_arr], label_rows=n_arr, label_cols=k_arr, label_axis_cols="$k$", label_axis_rows="$n$", title='$(-2, -1)$-Displaced Pascal Triangle:')

D:\fperotto\SourceCode\PyRL\src\pyrl\utils.py:54: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  dfs = dfs.applymap(lambda v : "color: lightgray" if v==0 else ("color: yellow" if v<0 else "color: black") )

## In resume : displacing the Pascal Triangle

If we see the cell $0, 0$ as the origin of the triangle, where the perturbation is introduced in the space, we can also imagine that this position could be changed.

For the valid binomial coefficients, it means:

### Delay

Let's call *delay* the modification on the axis $n$ :

$$ \mathcal{Delay}_d{\binom{n}{k}} = \binom{n-d}{k} $$

### Shifting

Let's call *shift* the modification on the axis $k$ :

$$ \mathcal{Shift}_b{\binom{n}{k}} = \binom{n}{k-b} $$

### Translating

$$ \mathcal{T}\!\mathcal{rans}_{d,b}{\binom{n}{k}} = \binom{n-d}{k-b} $$

In [2]:
max_k = 15
s_arr = range(-3,max_k+1)
n_arr = range(-3,max_k+1)

printdf([[zcomb(n, s) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n",  title='Pascal Triangle:', transpose=True, reverse=True )
printdf([[zshift(n, s, +5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n",  title='$+5$-Shifted Pascal Triangle:', transpose=True, reverse=True)
printdf([[zdelay(n, s, +3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n",  title='$+3$-Delayed Pascal Triangle:', transpose=True, reverse=True)
printdf([[ztrans(n, s, +3, +5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n",  title='$+5$-Shifted $+3$-Delayed Pascal Triangle:', transpose=True, reverse=True)