# Pivoted and Other Mirrored Triangles


## $m$-Pivoted Triangle

Pivoting any matrix, and then any triangle, reversing the columns based on a pivot column $m$, can be done by:

$ \mathcal{Piv}_m \big[ Z^{r,c}_{d,b} \big] (n,s) \ = \ Z^{r,c}_{d,b}(n,2m-s) $


## $m$-Mirrored Triangle

Mirroring any matrix, and then any triangle, corresponds to making all the columns of a given side reflect the columns at equivalent distance in the other side of the pivot columns.

In a mirrored triangle, a parameter $m$ defines the pivot column from where the triangle becomes a mirror.
The pivot column remains unchanged, as well as any columns in one of its sides. 
In the mirrored side, the columns take the values from the correponding column at equivalent distance from $m$, but in the other side.

Such mirror operation can be done in different manners: lower (or left), upper (or right), inner, or outer.
The lower and upper mirroring operations are intuitive, and have a fixed sense.
Upper mirroring means replacing the columns after the pivot, at its right, i.e. $m+i, \forall i \geq 1$, with the columns $m-i$.
Lower mirroring means replacing the columns before the pivot, at its left, i.e. $m-i, \forall i \geq 1$, with the columns $m+i$.

However, inner and outer mirroring operations depend on the relative position of the mirror $m$ to the origin $b$.
The inner mirror makes the original triangle remains unchanged at the external part of the matrix, replacing the internal part.
The external mirror makes the original triangle remains unchanged at the internal part of the matrix, replacing the external part.
So, in inner and outer operations, the sense (left or right) of the mirror changes depending if $m > b$ or $m < b$.
After an inner mirroring, the original peak of the triangle disappears, while after an outer mirroring, the original peak appears twice.

Note that in mirrored versions, the cells are not necessarely equivalent to the sum of their two upper neighbors.

Note also that inner and outer operations are singular when $m=b$. In this case, mirroring returns $0$.

### Lower Mirroring:

$ \mathcal{Mirlow}_m \big[ Z^{r,c}_{d,b}  \big] (n,s) \ = \ Z^{r,c}_{d,b}(n, m+|m-s|) $

### Upper Mirroring:

$ \mathcal{Mirupp}_m \big[ Z^{r,c}_{d,b} \big] (n,s) \ = \ Z^{r,c}_{d,b}(n, m-|m-s|) $

### Inner Mirroring:

$ \mathcal{Mir}_m \big[ Z^{r,c}_{d,b} \big] (n,s) \ = \ 
\begin{cases} 
  Z^{r,c}_{d,b}\!\left(n \, , \, m+\frac{m-b}{|m-b|} \, |m-s|\right) & \text{if } m \neq b\\
  0 & \text{if } m = b\\
\end{cases}$

### Outer Mirroring:

$ \mathcal{Mirout}_m\big[ Z^{r,c}_{d,b} \big] (n,s)\ = \ 
\begin{cases} 
  Z^{r,c}_{d,b}\!\left(n \, , \, m-\frac{m-b}{|m-b|} \, |m-s|\right) & \text{if } m \neq b\\
  0 & \text{if } m = b\\
\end{cases}$

In [1]:
import pandas as pd

s_arr = range(-6,+7)

index = ['k', 'pivot', 'mirror pointing left replacing right', 'mirror pointing right replacing left', 'mirror pointing out replacing interior', 'mirror pointing center replacing exterior']

m=+2
b=0

columns = ['b' if s==b else 'm' if s==m else s for s in s_arr ]

data = [ 
         [s for s in s_arr], 
         [int(2*m-s) for s in s_arr], 
         [int(m-abs(m-s)) for s in s_arr], 
         [int(m+abs(m-s)) for s in s_arr], 
         [int(m+((m-b)//abs(m-b)*abs(m-s))) for s in s_arr],
         [int(m-((m-b)//abs(m-b)*abs(m-s))) for s in s_arr]
       ]

df = pd.DataFrame(data, columns=columns, index=index)
display(df)

m=-2
b=0

columns = ['b' if s==b else 'm' if s==m else s for s in s_arr ]

data = [ 
         [s for s in s_arr], 
         [int(2*m-s) for s in s_arr], 
         [int(m-abs(m-s)) for s in s_arr],
         [int(m+abs(m-s)) for s in s_arr],
         [int(m+((m-b)//abs(m-b)*abs(m-s))) for s in s_arr],
         [int(m-((m-b)//abs(m-b)*abs(m-s))) for s in s_arr]
       ]

df = pd.DataFrame(data, columns=columns, index=index)
display(df)

m=+2
b=+5

columns = ['b' if s==b else 'm' if s==m else s for s in s_arr ]

data = [ 
         [s for s in s_arr], 
         [int(2*m-s) for s in s_arr], 
         [int(m-abs(m-s)) for s in s_arr], 
         [int(m+abs(m-s)) for s in s_arr], 
         [int(m+((m-b)//abs(m-b)*abs(m-s))) for s in s_arr],
         [int(m-((m-b)//abs(m-b)*abs(m-s))) for s in s_arr]
       ]

df = pd.DataFrame(data, columns=columns, index=index)
display(df)

m=-2
b=-5

columns = ['b' if s==b else 'm' if s==m else s for s in s_arr ]

data = [ 
         [s for s in s_arr], 
         [int(2*m-s) for s in s_arr], 
         [int(m-abs(m-s)) for s in s_arr],
         [int(m+abs(m-s)) for s in s_arr],
         [int(m+((m-b)//abs(m-b)*abs(m-s))) for s in s_arr],
         [int(m-((m-b)//abs(m-b)*abs(m-s))) for s in s_arr]
       ]

df = pd.DataFrame(data, columns=columns, index=index)
display(df)

,-6,-5,-4,-3,-2,-1,b,1,m,3,4,5,6
k,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
pivot,10,9,8,7,6,5,4,3,2,1,0,-1,-2
mirror pointing left replacing right,-6,-5,-4,-3,-2,-1,0,1,2,1,0,-1,-2
mirror pointing right replacing left,10,9,8,7,6,5,4,3,2,3,4,5,6
mirror pointing out replacing interior,10,9,8,7,6,5,4,3,2,3,4,5,6
mirror pointing center replacing exterior,-6,-5,-4,-3,-2,-1,0,1,2,1,0,-1,-2

,-6,-5,-4,-3,m,-1,b,1,2,3,4,5,6
k,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
pivot,2,1,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10
mirror pointing left replacing right,-6,-5,-4,-3,-2,-3,-4,-5,-6,-7,-8,-9,-10
mirror pointing right replacing left,2,1,0,-1,-2,-1,0,1,2,3,4,5,6
mirror pointing out replacing interior,-6,-5,-4,-3,-2,-3,-4,-5,-6,-7,-8,-9,-10
mirror pointing center replacing exterior,2,1,0,-1,-2,-1,0,1,2,3,4,5,6

,-6,-5,-4,-3,-2,-1,0,1,m,3,4,b,6
k,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
pivot,10,9,8,7,6,5,4,3,2,1,0,-1,-2
mirror pointing left replacing right,-6,-5,-4,-3,-2,-1,0,1,2,1,0,-1,-2
mirror pointing right replacing left,10,9,8,7,6,5,4,3,2,3,4,5,6
mirror pointing out replacing interior,-6,-5,-4,-3,-2,-1,0,1,2,1,0,-1,-2
mirror pointing center replacing exterior,10,9,8,7,6,5,4,3,2,3,4,5,6

,-6,b,-4,-3,m,-1,0,1,2,3,4,5,6
k,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6
pivot,2,1,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10
mirror pointing left replacing right,-6,-5,-4,-3,-2,-3,-4,-5,-6,-7,-8,-9,-10
mirror pointing right replacing left,2,1,0,-1,-2,-1,0,1,2,3,4,5,6
mirror pointing out replacing interior,2,1,0,-1,-2,-1,0,1,2,3,4,5,6
mirror pointing center replacing exterior,-6,-5,-4,-3,-2,-3,-4,-5,-6,-7,-8,-9,-10

In [2]:
from pyrl.gr import *
from pyrl.utils import printdf

################

max_s = 15
s_arr = range(-max_s,max_s+1)
n_arr = range(-3,max_s+1)

printdf([[gen_triangle(n, s, w=1, r=1, c=0, d=0, b=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='Pascal Triangle:', transpose=True, reverse=True)

printdf([[lower_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$+3$-Lower-Mirrored Triangle:', transpose=True, reverse=True)
printdf([[upper_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$+3$-Upper-Mirrored Triangle:', transpose=True, reverse=True)
printdf([[inner_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$+3$-Inner-Mirrored Triangle:', transpose=True, reverse=True)
printdf([[outer_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$+3$-Outer-Mirrored Triangle:', transpose=True, reverse=True)

printdf([[lower_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-Lower-Mirrored Triangle:', transpose=True, reverse=True)
printdf([[upper_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-Upper-Mirrored Triangle:', transpose=True, reverse=True)
printdf([[inner_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-Inner-Mirrored Triangle:', transpose=True, reverse=True)
printdf([[outer_mirrored_triangle(n, s, w=1, r=1, c=0, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-Outer-Mirrored Triangle:', transpose=True, reverse=True)

printdf([[gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[inner_mirrored_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-inner-mirrored $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[outer_mirrored_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-outer-mirrored $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[inner_mirrored_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-inner-mirrored $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[outer_mirrored_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-outer-mirrored $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)

printdf([[gen_triangle(n, s, w=1, r=3, c=-2, d=0, b=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$(3,-2)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[inner_mirrored_triangle(n, s, w=1, r=3, c=-2, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-inner-mirrored $(3,-2)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[outer_mirrored_triangle(n, s, w=1, r=3, c=-2, d=0, b=0, m=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-outer-mirrored $(3,-2)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[inner_mirrored_triangle(n, s, w=1, r=3, c=-2, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-inner-mirrored $(3,-2)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[outer_mirrored_triangle(n, s, w=1, r=3, c=-2, d=0, b=0, m=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-outer-mirrored $(3,-2)$-rewarded triangle:', transpose=True, reverse=True)