# Extended Pascal Triangle to Negative Range

## Definition

The Pascal's triangle is classically defined as a triangular matrix on the space $\mathbb{N} \times \mathbb{N}$ of naturals numbers.

It forms a lower/left triangular matrix, as follows:

$\forall \ n, k \in \mathbb{N} :$

$ \binom{n}{k} = \begin{cases} 
  0 & \text{if } k>n \\
  1 & \text{if } k=0 \\
  \binom{n-1}{k-1} + \binom{n-1}{k} & \text{otherwise}
\end{cases}$

Each non-zero element can be calculated directly using the binomial coefficient:

$ \binom{n}{k} \ = \ C(n, k) \ = \ C^k_n \ = \ \frac{n!}{k!(n-k)!} \ , \ \forall \ n, k \in \mathbb{N} \mid n \geq k \geq 0$

In [1]:
from srl.gr import *
from srl.utils import printdf

################

max_n = 20
k_arr = range(0,max_n+1)
n_arr = range(0,max_n+1)

printdf([[zcomb(n, k) for k in k_arr] for n in n_arr], label_rows=n_arr, label_cols=k_arr, label_axis_cols="k", label_axis_rows="n", title='Classic Pascal Triangle (lower triangular matrix), $C(n,k)$:')

## Extension to negative integer domain

The classical Pascal Triangle can be straightforward extended into the negative part of $k$ axis by simply filling such cells with value $0$, which preserves (and even generalize) all of its properties.

However, extending the triangle into the negative part of $n$ axis is more complicated, if the intention is preserving identities.

### Neutral (Zero) Extension

A simple extension, which we call $\mathcal{Z}$ both to represent $\mathbb{Z}$, the extended domain of $k$ and $n$, but also to represent the value zero, $0$, with which the matrix is filled:

$\forall \ n, k \in \mathbb{Z} :$

$$ \mathcal{Z}\binom{n}{k} = \begin{cases} 
  0 & \text{if } n<0 \text{ or } k<0 \\
  1 & \text{if } k=n=0 \\
  C(n-1, k-1) + C(n-1, k) & \text{otherwise}
\end{cases} $$

Each non-zero element can be calculated directly using the binomial coefficient:

$$ \mathcal{Z}\binom{n}{k} = \begin{cases}
\binom{n}{k} & \text{if } n \geq k \geq 0 \\
0 & \text{otherwise}
\end{cases} $$

In this interpretation, the triangle is intuitivelly extended with value $0$ over the domain of negative integers.

It can be seen as $0$-filled matrix that respects the Pascal property, and into which a $1$ perturbation is introduced at the position $(0, 0)$:

$\mathcal{Z}\binom{n}{k} = \mathcal{Z}\binom{n-1}{k-1} + \mathcal{Z}\binom{n-1}{k} \ , \ \forall n, k \neq 0$

## In the literature

In the literature, two different propositions exist in order to extend the Pascal triangle to negative $n$:
 1. extending the entire column $C(n,0)=1, \forall n \in \mathbb{Z}$, which preserves the binomial property;
 2. or extending the entire diagonal $C(n,k)=1, \forall n=k \in \mathbb{Z}$, which preserves the exponential generative matrix.

### Binomial (Column) Extension

<img src="img/PascalExtension3.png" width=300 height=auto />

### Exponential (Diagonal) Extension

<img src="img/PascalExtension0.png" width=400 height=auto />

### Other

<img src="img/PascalExtension2.jpg" width=400 height=auto />