# Bounded Displaced Rewarded Triangles

## $\ell$-Bounded Triangle using Outer-Mirrored Difference

While a truncated triangle make appear negative values in the matrix, 
an exact method for bounding a triangle in a given column $\ell$ is subtracting its $\ell$-outer-mirrored version:

$ \mathcal{Bound}_\ell \big[ Z_{d,b}^{r,c}(n,d) \big] \ = \ Z_{d,b}^{r,c}(n,d) - \mathcal{Mir}_\ell \big[ Z_{d,b}^{r,c}(n,d) \big]$

Note that, thanks to the mirroring definition in the case $\ell=b$, which returns a $0$ matrix, the $0$-bounded triangle is equivalent to the orginal one.

In [1]:
from srl.gr import *
from srl.utils import printdf

################

max_s = 15
s_arr = range(-max_s,max_s+1)
n_arr = range(-3,max_s+1)

### Bounding the classic Pascal's triangle:

In [2]:

printdf([[bound_gen_triangle(n, s, w=1, r=1, c=0, d=0, b=0, h=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-bounded Pascal triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=0, d=0, b=0, h=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-bounded Pascal triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=0, d=0, b=0, h=1) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$1$-bounded Pascal triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=0, d=0, b=0, h=-1) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-1$-bounded Pascal triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=0, d=0, b=0, h=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$0$-bounded Pascal triangle:', transpose=True, reverse=True)

### Bounding the $(+1,-1)$-rewarded (i.e. centered) triangle

In [3]:
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-bounded $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-bounded $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=1) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$1$-bounded $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=-1) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-1$-bounded $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$0$-bounded $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)

In [4]:
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=2, h=4) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$4$-bounded $2$-budgeted $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=-2, h=-4) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-4$-bounded $-2$-budgeted $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=5, h=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-bounded $5$-budgeted $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=-5, h=-3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-3$-bounded $-5$-budgeted $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)

printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=-5, h=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-bounded $-5$-budgeted $(1,-1)$-rewarded triangle:', transpose=True, reverse=True)