# Surviving Triangle

The surviving triangle is a budgeted triangle (i.e. centered then shifted) truncated at zero.

$\begin{align}
\mathcal{Surv}_{b}\mathcal{Z}\binom{n}{s}
\ & = \ \mathcal{Budget}_{b}\mathcal{Z}\binom{n}{s} - \mathcal{Budget}_{-b}\mathcal{Z}\binom{n}{s}\\
\ & = \ \begin{cases} 
  \mathcal{Z}\binom{n}{\frac{n+s-b}{2}} - \mathcal{Z}\binom{n}{\frac{n+s+b}{2}} & \text{if } \frac{n + s \pm b}{2} \in \mathbb{N} \\
  0 & \text{otherwise}
\end{cases}
\end{align}$

In [1]:
from pyrl.gr import *
from pyrl.utils import printdf

################

max_s = 20
s_arr = range(-max_s,max_s+1)
n_arr = range(-3,max_s+1)

printdf([[trunc_budget_triangle(n, s, 5, 0)    for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$0$-Truncated $+5$-Centered Triangle:', transpose=True, reverse=True)