# Bounded Centered and Budgeted Triangles

## $h$-Bounded Triangle using Mirrored Difference

While a truncated triangle make appear negative values in the matrix, 
an exact method for bounding a triangle in a given column $h$ is subtracting its $h$-mirrored version:

$ \mathcal{Bound}_hZ_b (n,d) \ = \ Z_b(n,d) - \mathcal{Mir}_h \big[ Z_b \big] (n,d)$

In [1]:
from pyrl.gr import *
from pyrl.utils import printdf

################

max_s = 15
s_arr = range(-max_s,max_s+1)
n_arr = range(-3,max_s+1)

### Bounding the $(+1,-1)$-rewarded (i.e. centered) triangle

In [2]:
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-bounded centered triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-bounded centered triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=1) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$1$-bounded centered triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=-1) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-1$-bounded centered triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=0, h=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$0$-bounded centered triangle:', transpose=True, reverse=True)

D:\fperotto\SourceCode\PyRL\src\pyrl\utils.py:54: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  dfs = dfs.applymap(lambda v : "color: lightgray" if v==0 else ("color: yellow" if v<0 else "color: black") )

D:\fperotto\SourceCode\PyRL\src\pyrl\utils.py:54: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  dfs = dfs.applymap(lambda v : "color: lightgray" if v==0 else ("color: yellow" if v<0 else "color: black") )

D:\fperotto\SourceCode\PyRL\src\pyrl\utils.py:54: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  dfs = dfs.applymap(lambda v : "color: lightgray" if v==0 else ("color: yellow" if v<0 else "color: black") )

D:\fperotto\SourceCode\PyRL\src\pyrl\utils.py:54: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  dfs = dfs.applymap(lambda v : "color: lightgray" if v==0 else ("color: yellow" if v<0 else "color: black") )

D:\fperotto\SourceCode\PyRL\src\pyrl\utils.py:54: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  dfs = dfs.applymap(lambda v : "color: lightgray" if v==0 else ("color: yellow" if v<0 else "color: black") )

In [3]:
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=5, h=0) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$0$-bounded $5$-budgeted triangle:', transpose=True, reverse=True)
printdf([[ruin_budget_triangle(n, s, b=5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='Ruined $5$-budgeted triangle:', transpose=True, reverse=True)

printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=2, h=4) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$4$-bounded $2$-budgeted triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=4, h=2) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$2$-bounded $4$-budgeted triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=-2, h=-4) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-4$-bounded $-2$-budgeted triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=5, h=3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$3$-bounded $5$-budgeted triangle:', transpose=True, reverse=True)
printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=-5, h=-3) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-3$-bounded $-5$-budgeted triangle:', transpose=True, reverse=True)

printdf([[bound_gen_triangle(n, s, w=1, r=1, c=-1, d=0, b=-5, h=-5) for s in s_arr] for n in n_arr], label_rows=n_arr, label_cols=s_arr, label_axis_cols="s", label_axis_rows="n", title='$-5$-bounded $-5$-budgeted triangle:', transpose=True, reverse=True)